import type { Task } from './task'

export const mockTasks: Task[] = [
  {
    assignee: { id: 'user-lena-evans', initials: 'LE', name: 'Lena Evans' },
    attachmentCount: 2,
    checklistCount: 5,
    commentCount: 3,
    dueDate: '2026-08-04',
    dueDateLabel: 'Today',
    dueDateTone: 'soon',
    id: 'task-1',
    pointEstimate: 'FOUR',
    status: 'BACKLOG',
    tags: ['IOS', 'ANDROID'],
    title: 'Slack workspace',
  },
  {
    attachmentCount: 1,
    checklistCount: 2,
    commentCount: 1,
    dueDate: '2026-08-10',
    dueDateLabel: '10 Aug, 2026',
    dueDateTone: 'future',
    id: 'task-2',
    pointEstimate: 'TWO',
    status: 'BACKLOG',
    tags: ['REACT'],
    title: 'Research task insights',
  },
  {
    assignee: { id: 'mock-authenticated-user', initials: 'FE', name: 'Fabian Espinoza' },
    attachmentCount: 3,
    checklistCount: 4,
    commentCount: 2,
    dueDate: '2026-08-05',
    dueDateLabel: 'Tomorrow',
    dueDateTone: 'soon',
    id: 'task-3',
    pointEstimate: 'TWO',
    status: 'TODO',
    tags: ['IOS', 'ANDROID'],
    title: 'Google calendar sync',
  },
  {
    assignee: { id: 'mock-authenticated-user', initials: 'FE', name: 'Fabian Espinoza' },
    attachmentCount: 2,
    checklistCount: 5,
    commentCount: 3,
    dueDate: '2026-08-03',
    dueDateLabel: 'Yesterday',
    dueDateTone: 'past',
    id: 'task-4',
    pointEstimate: 'ONE',
    status: 'IN_PROGRESS',
    tags: ['IOS', 'ANDROID'],
    title: 'Twitter notification flow',
  },
  {
    assignee: { id: 'user-alex-lee', initials: 'AL', name: 'Alex Lee' },
    attachmentCount: 1,
    checklistCount: 3,
    commentCount: 2,
    dueDate: '2026-08-06',
    dueDateLabel: '6 Aug, 2026',
    dueDateTone: 'future',
    id: 'task-5',
    pointEstimate: 'FOUR',
    status: 'IN_PROGRESS',
    tags: ['REACT'],
    title: 'Maxxis tyres dashboard',
  },
  {
    assignee: { id: 'mock-authenticated-user', initials: 'FE', name: 'Fabian Espinoza' },
    attachmentCount: 4,
    checklistCount: 6,
    commentCount: 2,
    dueDate: '2026-08-12',
    dueDateLabel: '12 Aug, 2026',
    dueDateTone: 'future',
    id: 'task-6',
    pointEstimate: 'EIGHT',
    status: 'DONE',
    tags: ['IOS', 'ANDROID'],
    title: 'Tesla mobile handoff',
  },
  {
    assignee: { id: 'mock-authenticated-user', initials: 'FE', name: 'Fabian Espinoza' },
    attachmentCount: 2,
    checklistCount: 5,
    commentCount: 3,
    dueDate: '2026-08-04',
    dueDateLabel: 'Today',
    dueDateTone: 'soon',
    id: 'task-7',
    pointEstimate: 'FOUR',
    status: 'DONE',
    tags: ['REACT', 'ANDROID'],
    title: 'Slack release checklist',
  },
  {
    assignee: { id: 'user-jordan-rivera', initials: 'JR', name: 'Jordan Rivera' },
    attachmentCount: 1,
    checklistCount: 1,
    commentCount: 0,
    dueDate: '2026-08-02',
    dueDateLabel: '2 Aug, 2026',
    dueDateTone: 'past',
    id: 'task-8',
    pointEstimate: 'TWO',
    status: 'CANCELLED',
    tags: ['ANDROID'],
    title: 'Legacy Android experiment',
  },
]
